name: smoke
version: 0.3.4
author: Polymer.dart Authors <web-ui-dev@dartlang.org>
description: A restricted reflective system that uses mirrors at development time, but that can be replaced with non-reflective calls using code generation. See README.md for mode details.
homepage: https://github.com/dart-lang/smoke
environment:
  sdk: '>=1.3.0-dev.7.9 <2.0.0'
dependencies:
  analyzer: '>=0.13.0 <0.26.0'
  barback: '>=0.9.0 <0.16.0'
  logging: '>=0.9.0 <0.12.0'
dev_dependencies:
  code_transformers: '>=0.2.0 <0.3.0'
  path: '>=1.0.0 <2.0.0'
  unittest: '>=0.10.0 <0.12.0'
transformers:
- smoke/src/default_transformer:
    $include: lib/src/implementation.dart
