name: smoke
version: 0.1.0-dev
author: Polymer.dart Authors <web-ui-dev@dartlang.org>
homepage: "https://api.dartlang.org/apidocs/channels/be/#smoke"
description: >
  A restricted reflective system that uses mirrors at development time, but that
  can be replaced with non-reflective calls using code generation. See README.md
  for mode details.
dependencies:
  barback: ">=0.9.0 <0.12.0"
  logging: ">=0.9.0 <0.10.0"
# TODO(sigmund): uncomment this once we have some easier way to do global
# app-level transformers or a way to enable this selectively from the
# application package.
#transformers:
#- smoke/src/default_transformer:
#    # TODO(sigmund): include this once this feature is available in the stable
#    # channel, or when we really need some other feature in the dev channel.
#    $include: lib/src/implementation.dart
dev_dependencies:
  unittest: ">=0.10.0 <0.11.0"
  path: ">=1.0.0 <2.0.0"
environment:
  sdk: ">=1.2.0 <2.0.0"
