name: smoke
version: 0.1.0-dev
author: Polymer.dart Authors <web-ui-dev@dartlang.org>
description: >
  A restricted reflective system that uses mirrors at development time, but that
  can be replaced with non-reflective calls using code generation. See README.md
  for mode details.
dependencies:
  barback: ">=0.9.0 <0.12.0"
  logging: ">=0.9.0 <0.10.0"
transformers: [smoke/src/default_transformer]
dev_dependencies:
  unittest: ">=0.9.0 <0.10.0"
environment:
  sdk: ">=1.1.0-dev.5.0 <2.0.0"
